import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
  blogSidebar: [{ type: "autogenerated", dirName: "blog" }],
  hackBlogSidebar: [{ type: "autogenerated", dirName: "hack_blog" }],
  // hackBlogSidebar: [
  //   {
  //     type: "category",
  //     label: "CTF Tournaments",
  //     items: [
  //       {
  //         type: "category",
  //         label: "Angstrom CTF",
  //         items: [
  //           "hack_blog/angstrom_2022/crypto/caesar_and_desister/README.md",
  //           "hack_blog/angstrom_2022/misc/confetti/README.md",
  //           "hack_blog/angstrom_2022/reverse_engineering/baby3/README.md",
  //           "hack_blog/angstrom_2022/web/the_flash/README.md",
  //         ],
  //       },
  //       {
  //         type: "category",
  //         label: "PicoCTF",
  //         items: [
  //           "hack_blog/pico_2022/binary_exploitation/basic_file_exploit/README.md",
  //           "hack_blog/pico_2022/binary_exploitation/buffer_overflow_0/README.md",
  //           "hack_blog/pico_2022/binary_exploitation/buffer_overflow_1/README.md",
  //           "hack_blog/pico_2022/binary_exploitation/buffer_overflow_2/README.md",
  //           "hack_blog/pico_2022/binary_exploitation/buffer_overflow_3/README.md",
  //         ],
  //       },
  //     ],
  //   },
  // ],
};

export default sidebars;
